from django.db import models  

class drop_down(models.Model):
    DropDownName        = models.CharField(max_length=250, blank=True)
    DropDownValue       = models.CharField(max_length=250, blank=True)
    DropDownDescription = models.TextField(blank=True)
    Parent              = models.CharField(max_length=250, blank=True)
    Data                = models.TextField(blank=True)	
    CreatedBy           = models.CharField(max_length=200, blank=True)
    UpdatedBy           = models.CharField(max_length=200, blank=True)
    CreateDate          = models.CharField(max_length=200, blank=True)
    CreateTime          = models.CharField(max_length=200, blank=True)
    UpdateDate          = models.CharField(max_length=200, blank=True)
    UpdateTime          = models.CharField(max_length=200, blank=True)


class static_drop_down(models.Model):
    DropDownName        = models.CharField(max_length=250, blank=True)
    DropDownValue       = models.CharField(max_length=250, blank=True)
    DropDownDescription = models.TextField(blank=True)	
    Parent              = models.CharField(max_length=250, blank=True)


class country(models.Model):
    region_name         = models.CharField(max_length=200, blank=True, null=True)
    country_name        = models.CharField(max_length=200, blank=True, null=True)
    country_code        = models.CharField(max_length=200, blank=True, null=True)
    country_flag_code   = models.CharField(max_length=50, blank=True, null=True)
    is_active           = models.IntegerField(default=1)
    local_currency_code = models.CharField(max_length=200, blank=True, null=True)  
    local_currency      = models.CharField(max_length=200, blank=True, null=True)  
    symbol              = models.CharField(max_length=200, blank=True)  
    gbp_average         = models.CharField(max_length=200, blank=True, null=True)  
    usd_average         = models.CharField(max_length=200, blank=True, null=True)  
    euro_average        = models.CharField(max_length=200, blank=True, null=True)  
    added_by            = models.CharField(max_length=200, blank=True, null=True)
    added_on            = models.DateTimeField(auto_now_add=True)  
    update_on           = models.DateTimeField(auto_now=True)  


class monthly_baseline(models.Model):
    emp_ref_no          = models.CharField(max_length=20, blank=True, null=True)
    current_job         = models.CharField(max_length=200, blank=True, null=True)
    emp_grade           = models.CharField(max_length=200, blank=True, null=True)
    emp_function        = models.CharField(max_length=200, blank=True, null=True)
    region              = models.CharField(max_length=200, blank=True, null=True)  
    emp_bu              = models.CharField(max_length=200, blank=True, null=True)  
    emp_e_date          = models.CharField(max_length=200, blank=True, null=True)
    fte                 = models.CharField(max_length=200, blank=True, null=True)  
    sga_indirect        = models.CharField(max_length=200, blank=True, null=True)  
    sup_name            = models.CharField(max_length=200, blank=True, null=True)
    sup_job_title       = models.CharField(max_length=200, blank=True, null=True)
    local_currency      = models.CharField(max_length=200, blank=True, null=True)
    annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)
    allowance_total     = models.CharField(max_length=200, blank=True, null=True)
    car_allowance       = models.CharField(max_length=200, blank=True, null=True)
    commision_plan      = models.CharField(max_length=200, blank=True, null=True)
    bonus               = models.CharField(max_length=200, blank=True, null=True)
    t_month             = models.IntegerField(default=0)
    t_year              = models.IntegerField(default=0)
    country             = models.CharField(max_length=200, blank=True, null=True)  
    key_pair            = models.CharField(max_length=200, null=True, blank=True)  
    is_processed        = models.IntegerField(default = 0)  
    summery_key         = models.CharField(max_length=200, blank=True, null=True)
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    empno_bu_key        = models.CharField(max_length=200, blank=True, null=True)
    record_region       = models.CharField(max_length=200, blank=True, null=True)
    new_j_p_name        = models.CharField(max_length=200, blank=True, null=True)
    new_j_pos_id        = models.CharField(max_length=200, blank=True, null=True)
    position_end_date   = models.DateField(blank=True, null=True)
    new_annual_amount   = models.CharField(max_length=200, blank=True, null=True)
    # new fields
    total_cost          = models.CharField(max_length=200, blank=True, null=True)
    payroll_burden      = models.CharField(max_length=200, blank=True, null=True)
    pos_gross_pay       = models.CharField(max_length=200, blank=True, null=True)
    pos_net_pay         = models.CharField(max_length=200, blank=True, null=True)
    postion_baseline_total  = models.CharField(max_length=200, blank=True, null=True)

    # currency related fields
    gbp_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    usd_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    euro_annual_base_pay    = models.CharField(max_length=200, blank=True, null=True) 
    gbp_new_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    usd_new_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    euro_new_annual_base_pay    = models.CharField(max_length=200, blank=True, null=True) 


class yearly_baseline(models.Model):
    emp_ref_no          = models.CharField(max_length=20, blank=True, null=True)
    current_job         = models.CharField(max_length=200, blank=True, null=True)
    emp_grade           = models.CharField(max_length=200, blank=True, null=True)
    emp_function        = models.CharField(max_length=200, blank=True, null=True)
    region              = models.CharField(max_length=200, blank=True, null=True)
    emp_bu              = models.CharField(max_length=200, blank=True, null=True)
    emp_e_date          = models.CharField(max_length=200, blank=True, null=True)
    fte                 = models.CharField(max_length=200, blank=True, null=True)
    sga_indirect        = models.CharField(max_length=200, blank=True, null=True)
    sup_name            = models.CharField(max_length=200, blank=True, null=True)
    sup_job_title       = models.CharField(max_length=200, blank=True, null=True)
    annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)
    allowance_total     = models.CharField(max_length=200, blank=True, null=True)
    bonus               = models.CharField(max_length=200, blank=True, null=True)
    car_allowance       = models.CharField(max_length=200, blank=True, null=True)
    commision_plan      = models.CharField(max_length=200, blank=True, null=True)
    t_month             = models.IntegerField(default=0)
    t_year              = models.IntegerField(default=0)
    country             = models.CharField(max_length=200, blank=True, null=True)
    key_pair            = models.CharField(max_length=200, null=True, blank=True)
    is_processed        = models.IntegerField(default = 0)
    summery_key         = models.CharField(max_length=200, blank=True, null=True)
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    position_start_date = models.DateTimeField(blank=True, null=True)
    position_end_date   = models.DateField(blank=True, null=True)
    issync              = models.IntegerField(default = 0) 
    record_region       = models.CharField(max_length=200, blank=True, null=True)
    is_active           = models.IntegerField(default = 1)
    local_currency      = models.CharField(max_length=200, blank=True, null=True)
    new_annual_amount   = models.CharField(max_length=200, blank=True, null=True)
    # new keys
    total_cost          = models.CharField(max_length=200, blank=True, null=True)
    payroll_burden      = models.CharField(max_length=200, blank=True, null=True)
    pos_gross_pay       = models.CharField(max_length=200, blank=True, null=True)
    pos_net_pay         = models.CharField(max_length=200, blank=True, null=True)
    postion_baseline_total  = models.CharField(max_length=200, blank=True, null=True)

    # currency related fields
    gbp_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    usd_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    euro_annual_base_pay    = models.CharField(max_length=200, blank=True, null=True) 
    gbp_new_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    usd_new_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    euro_new_annual_base_pay    = models.CharField(max_length=200, blank=True, null=True) 

class position(models.Model):
    emp_ref_no          = models.CharField(max_length=20, blank=True, null=True)
    region              = models.CharField(max_length=200, blank=True, null=True)
    country             = models.CharField(max_length=200, blank=True, null=True)
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    position_name       = models.CharField(max_length=500, blank=True, null=True)
    baseline_total      = models.FloatField()
    baseline_year       = models.TextField(blank=True, null=True)  # This field type is a guess.
    created_date        = models.DateTimeField(auto_now_add=True)
    requester_email     = models.CharField(max_length=200, blank=True, null=True)
    status              = models.IntegerField(default=0)#'0-Pending with Country HR, 2-Pending with Hroup HR, 1- Approved' 
    regional_hr         = models.CharField(max_length=200, blank=True, null=True)
    is_vacant           = models.IntegerField(default=1) # 1-Vacant 0-No Vacant
    is_active           = models.IntegerField(default=1) # 1-Yes, 0-No '0 set if Redundant measns position close (discard)'
    is_delta            = models.IntegerField(default=0) #'0-Vacant, 1-Assigned, 2-Redundant'
    pos_grade           = models.CharField(max_length=200, blank=True, null=True)
    pos_function        = models.CharField(max_length=150, blank=True, null=True)
    pos_bu              = models.CharField(max_length=200, blank=True, null=True)
    pos_fte             = models.CharField(max_length=200, blank=True, null=True)
    pos_type            = models.CharField(max_length=200, blank=True, null=True)
    pos_manager_emp_id  = models.CharField(max_length=200, blank=True, null=True) #manager emp_ref_no
    pos_manager         = models.CharField(max_length=200, blank=True, null=True)
    pos_manager_job_title = models.CharField(max_length=500, blank=True, null=True)
    pos_add_cash        = models.CharField(max_length=200, blank=True, null=True)
    pos_bonus           = models.CharField(max_length=200, blank=True, null=True)
    pos_add_remark      = models.TextField(blank=True, null=True)
    regionalhr_comment  = models.TextField(blank=True, null=True)  
    approver_group_hr   = models.CharField(max_length=200, blank=True, null=True)
    approver_group_comment = models.TextField(blank=True, null=True)
    amount_based_approval  = models.IntegerField(default=0)
    pos_return_invest_remark = models.TextField(blank=True, null=True)
    pos_local_curr      = models.CharField(max_length=200, blank=True, null=True)
    pos_car_allowance   = models.CharField(max_length=200, blank=True, null=True)
    approver_2_email    = models.CharField(max_length=200, blank=True, null=True)
    approver_2_remark   = models.TextField(blank=True, null=True)
    pos_currency        = models.CharField(max_length=200, blank=True, null=True)
    new_annual_amount   = models.CharField(max_length=200, blank=True, null=True)
    is_approved         = models.IntegerField(default=0)
    pos_car_allowance_type = models.CharField(max_length=200, blank=True, null=True)
    pos_end_date        = models.DateField(blank=True, null=True)
    pos_revenue         = models.CharField(max_length=50, blank=True, null=True)
    pos_ebita           = models.CharField(max_length=50, blank=True, null=True)
    pos_ocf             = models.CharField(max_length=50, blank=True, null=True)
    pos_netcashflow     = models.CharField(max_length=50, blank=True, null=True)
    position_grossprofit = models.CharField(max_length=50, blank=True, null=True)  
    position_grossmargin = models.CharField(max_length=50, blank=True, null=True)  
    eff_from            = models.DateField(blank=True, null=True)
    pos_commision_plan  = models.CharField(max_length=200, blank=True, null=True)
    pos_cxo_tasking     = models.IntegerField(default=0)
    pos_gross_pay       = models.CharField(max_length=200, blank=True, null=True)
    pos_net_pay         = models.CharField(max_length=200, blank=True, null=True)
    pos_manager_number  = models.CharField(max_length=200, blank=True, null=True)
    pos_price_increase  = models.CharField(max_length=200, blank=True, null=True)
    is_revenue_generating = models.IntegerField(default=0)
    end_date            = models.DateField(blank=True, null=True)
    pos_contract_type   = models.CharField(max_length=200, blank=True, null=True)
    total_cost          = models.CharField(max_length=200, blank=True, null=True)
    payroll_burden      = models.CharField(max_length=200, blank=True, null=True)

    # fields for pleaning
    plane_role_start_date   = models.CharField(max_length=200, blank=True, null=True)
    plane_role_end_date     = models.CharField(max_length=200, blank=True, null=True)
    plane_severance         = models.CharField(max_length=200, blank=True, null=True)

    position_pos_bonus      = models.CharField(max_length=200, blank=True, null=True)
    postion_baseline_total  = models.CharField(max_length=200, blank=True, null=True)
    actual_severance        = models.CharField(max_length=200, blank=True, null=True)
    position_pos_add_cash   = models.CharField(max_length=200, blank=True, null=True)
    planned_increase        = models.CharField(max_length=200, blank=True, null=True)
    actual_increase         = models.CharField(max_length=200, blank=True, null=True)
    pos_annual_total_cost   = models.CharField(max_length=200, blank=True, null=True)
    agreed_plan             = models.CharField(max_length=200, blank=True, null=True)
    emp_start_date          = models.CharField(max_length=200, blank=True, null=True)
    emp_end_date            = models.CharField(max_length=200, blank=True, null=True)

    # currency related fields
    gbp_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    usd_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    euro_annual_base_pay    = models.CharField(max_length=200, blank=True, null=True) 
    gbp_new_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    usd_new_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    euro_new_annual_base_pay    = models.CharField(max_length=200, blank=True, null=True) 
    # new keys 
    pos_remarks         = models.CharField(max_length=200, blank=True, null=True)
    emp_remarks         = models.CharField(max_length=200, blank=True, null=True)
    emp_reason          = models.CharField(max_length=200, blank=True, null=True)
    updated_by          = models.CharField(max_length=200, blank=True, default="")
    created_by          = models.CharField(max_length=200, blank=True, default="")
    oe_remarks          = models.CharField(max_length=200, blank=True, null=True)
    emp_status          = models.CharField(max_length=200, blank=True, null=True, default='Vacant')


class position_history(models.Model):
    action_type         = models.CharField(max_length=200, blank=True, null=True) # vacant, re-open, closed
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    emp_ref_no          = models.CharField(max_length=200, blank=True, null=True)
    emp_reason          = models.CharField(max_length=200, blank=True, null=True)
    remarks             = models.TextField(blank=True)
    updated_by          = models.CharField(max_length=200, blank=True, default="")
    eff_from            = models.CharField(max_length=200, blank=True, default="")
    pos_end_date        = models.CharField(max_length=200, blank=True, default="")
    created_date        = models.DateTimeField(auto_now_add=True)
    updated_date        = models.DateTimeField(auto_now=True)

class employee_history(models.Model):
    action_type         = models.CharField(max_length=200, blank=True, null=True) # assign, leave
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    emp_ref_no          = models.CharField(max_length=200, blank=True, null=True)
    emp_start_date      = models.CharField(max_length=200, blank=True, null=True)
    emp_end_date        = models.CharField(max_length=200, blank=True, null=True)
    postion_baseline_total = models.CharField(max_length=200, blank=True, null=True)
    pos_gross_pay       = models.CharField(max_length=200, blank=True, null=True)
    pos_net_pay         = models.CharField(max_length=200, blank=True, null=True)
    position_pos_add_cash = models.CharField(max_length=200, blank=True, null=True)
    position_pos_bonus  = models.CharField(max_length=200, blank=True, null=True)
    pos_car_allowance_type = models.CharField(max_length=200, blank=True, null=True)
    pos_car_allowance   = models.CharField(max_length=200, blank=True, null=True)
    pos_commision_plan  = models.CharField(max_length=200, blank=True, null=True)
    total_cost          = models.CharField(max_length=200, blank=True, null=True)
    new_annual_amount   = models.CharField(max_length=200, blank=True, null=True)
    emp_reason          = models.CharField(max_length=200, blank=True, null=True)
    remarks             = models.TextField(blank=True)
    updated_by          = models.CharField(max_length=200, blank=True, default="")
    created_date        = models.DateTimeField(auto_now_add=True)
    updated_date        = models.DateTimeField(auto_now=True)


class position_action_approvel_request(models.Model):
    action_type         = models.CharField(max_length=200, blank=True, null=True) # vacant, assign, pay-increase
    record_region       = models.CharField(max_length=200, blank=True, null=True)
    record_country      = models.CharField(max_length=200, blank=True, null=True)
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    emp_ref_no          = models.CharField(max_length=200, blank=True, null=True)
    reason              = models.CharField(max_length=200, blank=True, null=True)
    reason_details      = models.CharField(max_length=200, blank=True, null=True)
    requsted_by_remarks = models.CharField(max_length=200, blank=True, default="")
    approved_by_remarks = models.CharField(max_length=200, blank=True, default="")
    approved_by         = models.CharField(max_length=200, blank=True, default="")
    requsted_by         = models.CharField(max_length=200, blank=True, default="")
    pos_end_date        = models.CharField(max_length=200, blank=True, default="")
    status              = models.IntegerField(default=0) # 0-pending, 1-accept, 2-reject
    created_date        = models.DateTimeField(auto_now_add=True)
    updated_date        = models.DateTimeField(auto_now=True)

class annual_summary(models.Model):
    record_country      = models.CharField(max_length=200, blank=True, null=True)
    record_year         = models.IntegerField(default=0)
    record_month        = models.IntegerField(default=0)
    emp_total_count     = models.IntegerField(default=0)
    emp_new_count       = models.IntegerField(default=0)
    emp_left_count      = models.IntegerField(default=0)
    monthly_gross_payout = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    left_gross_payout   = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    status              = models.IntegerField(default=0)
    created_date        = models.DateTimeField(auto_now_add=True)
    uploaded_by         = models.CharField(max_length=200, blank=True, null=True)
    security_code       = models.CharField(max_length=50, blank=True, null=True)
    is_security_code_used = models.IntegerField(default=0)
    sheet_key           = models.CharField(max_length=200, blank=True, null=True)
    ymd_date            = models.DateField(blank=True, null=True)
    sheet_url           = models.CharField(max_length=200, blank=True, null=True)
    issync              = models.IntegerField(blank=True, null=True)  
    record_region       = models.CharField(max_length=200, blank=True, null=True)
    # currency related fields
    gbp_gross_payout     = models.CharField(max_length=200, blank=True, null=True)  
    usd_gross_payout     = models.CharField(max_length=200, blank=True, null=True)  
    euro_gross_payout    = models.CharField(max_length=200, blank=True, null=True)


class monthly_summary(models.Model):
    record_country      = models.CharField(max_length=200, blank=True, null=True)
    record_year         = models.IntegerField(default=0)
    record_month        = models.IntegerField(default=0)
    emp_total_count     = models.IntegerField(default=0)
    emp_new_count       = models.IntegerField(default=0)
    emp_left_count      = models.IntegerField(default=0)
    monthly_gross_payout = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    status              = models.IntegerField(default=0)
    created_date        = models.DateTimeField(auto_now_add=True)
    uploaded_by         = models.CharField(max_length=200, blank=True, null=True)
    security_code       = models.CharField(max_length=50, blank=True, null=True)
    is_security_code_used = models.IntegerField(default=0)
    sheet_key           = models.CharField(max_length=200, blank=True, null=True)
    ymd_date            = models.DateField(blank=True, null=True)
    sheet_url           = models.CharField(max_length=200, blank=True, null=True)
    record_region       = models.CharField(max_length=200, blank=True, null=True)
    # currency related fields
    gbp_gross_payout     = models.CharField(max_length=200, blank=True, null=True)  
    usd_gross_payout     = models.CharField(max_length=200, blank=True, null=True)  
    euro_gross_payout    = models.CharField(max_length=200, blank=True, null=True)


class position_other_pay(models.Model):
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    component_type      = models.CharField(max_length=155, blank=True, null=True)
    component_desc      = models.TextField(blank=True, null=True)
    component_amount    = models.CharField(max_length=200, blank=True, null=True)

class position_workflow(models.Model):
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    ceo_comment         = models.TextField(blank=True, null=True)
    approval_rule       = models.CharField(max_length=200, blank=True, null=True)
    is_approval_completed = models.IntegerField(default=0)


class delta_monthly(models.Model):
    position_id         = models.CharField(max_length=200, blank=True, null=True)
    status              = models.CharField(max_length=200, blank=True, null=True)
    base_pay_monthly    = models.CharField(max_length=200, blank=True, null=True)
    month               = models.CharField(max_length=200, blank=True, null=True)
    year                = models.CharField(max_length=200, blank=True, null=True)
    closed_date         = models.CharField(max_length=200, blank=True, null=True)
    country             = models.CharField(max_length=200, blank=True, null=True)
    emp_ref_no          = models.CharField(max_length=200, blank=True, null=True)
    emp_bu              = models.CharField(max_length=200, blank=True, null=True)
    curr_summery_key    = models.CharField(max_length=200, blank=True, null=True)
    current_job         = models.CharField(max_length=200, blank=True, null=True)
    position_type       = models.CharField(max_length=200, blank=True, null=True)
    sga_direct          = models.CharField(max_length=200, blank=True, null=True)
    record_region       = models.CharField(max_length=200, blank=True, null=True)
    is_recon            = models.IntegerField(default=0)
    insert_date         = models.DateTimeField(auto_now_add=True)
    update_date         = models.DateTimeField(auto_now=True)
    gbp_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    usd_annual_base_pay     = models.CharField(max_length=200, blank=True, null=True)  
    euro_annual_base_pay    = models.CharField(max_length=200, blank=True, null=True) 

class file(models.Model):
    region              = models.CharField(max_length=200, blank=True, null=True)  
    country             = models.CharField(max_length=200, blank=True, null=True)  
    trackurl            = models.CharField(max_length=200, blank=True, null=True)  
    t_month             = models.IntegerField(default=0)
    t_year              = models.IntegerField(default=0)
    status              = models.IntegerField(default=0)
    uploaderemail       = models.CharField(max_length=200, blank=True, null=True)  
    iserror             = models.CharField(max_length=20, default="NO")  # NO|YES
    isreviewed          = models.IntegerField(default=0)
    isupload            = models.IntegerField(default=0)
    insert_date         = models.DateTimeField(auto_now_add=True)
    update_date         = models.DateTimeField(auto_now=True)
    

class event(models.Model):
    event_id            = models.CharField(unique=True, max_length=200, blank=True, null=True)
    event_description   = models.CharField(max_length=255, blank=True, null=True)
    cerated_by          = models.CharField(max_length=200, blank=True, null=True)
    created_on          = models.DateTimeField(auto_now_add=True)
    status              = models.IntegerField(default=0)

class audit_history(models.Model):
    pos_id              = models.CharField(max_length=200, blank=True, null=True)
    action_by           = models.CharField(max_length=200, blank=True, null=True)
    action_desc         = models.CharField(max_length=500, blank=True, null=True)
    other_detail        = models.CharField(max_length=500, blank=True, null=True)
    created_on          = models.DateTimeField(auto_now_add=True)

class activity_history(models.Model):
    field_id            = models.IntegerField(blank=True, null=True)
    field_name          = models.CharField(max_length=200, blank=True, null=True)
    field_old_value     = models.CharField(max_length=500, blank=True, null=True)
    field_new_value     = models.CharField(max_length=500, blank=True, null=True)
    created_by          = models.CharField(max_length=222, blank=True, null=True)
    status              = models.IntegerField(default=0)#'0-Pending, 1- Approved'
    effective_date      = models.DateTimeField(blank=True, null=True)
    created_at          = models.DateTimeField(auto_now_add=True)
    
class position_files(models.Model):
    position = models.ForeignKey(position, on_delete=models.CASCADE, related_name='position_files_history')
    file_name = models.CharField(max_length=200, blank=True, null=True)
    file_url = models.CharField(max_length=500, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)